// Educational traces derived from github_issue_agent/api.py (v0.1.0).
// These are deterministic illustrations, not real agent executions.
export const nodes = [
  { id: 'task', number: '01', name: 'Task & configuration', file: 'api.py · config.py', icon: 'terminal' },
  { id: 'context', number: '02', name: 'Repository context', file: 'context.py', icon: 'file' },
  { id: 'plan', number: '03', name: 'Planning', file: 'workflow.py · llm.py', icon: 'layers' },
  { id: 'implement', number: '04', name: 'Implementation', file: 'workflow.py · editor.py', icon: 'code' },
  { id: 'verify', number: '05', name: 'Verification', file: 'runner.py', icon: 'check' },
  { id: 'publish', number: '06', name: 'Git & pull request', file: 'git_ops.py · github_client.py', icon: 'branch' },
];

export const events = {
  task: { node: 'task', title: 'Resolve the task and settings', text: 'The CLI calls run_workflow(). The API resolves the target path, loads configuration, discovers the Markdown workflow, and prepares the issue or prompt.', input: 'Issue URL or prompt · target checkout · workflow name', output: 'Resolved configuration + task text', source: 'api.py', detail: 'An issue URL or open_pr=True initializes the GitHub client and requires a token. A dry run still performs this preparation.', log: 'TASK     Resolve config, workflow, and task input.' },
  context: { node: 'context', title: 'Let the repository set the rules', text: 'Instruction files and matching rule files are read, then a file tree is built. This is the context the planner sees before choosing source files.', input: 'AGENTS.md · README · .ai/rules/*.md · git ls-files', output: 'Instructions + rules + file tree', source: 'context.py', detail: 'The file tree is capped at 400 entries. Individual instruction and selected source files are truncated at 20,000 characters.', log: 'CONTEXT  Load instructions, rules, and the repository tree.' },
  plan: { node: 'plan', title: 'Choose what to change—and what to read', text: 'The provider receives the workflow, instructions, file tree, and task. Its structured response names the files to inspect and the implementation steps.', input: 'Workflow + context + task', output: 'understanding · files_to_read · steps', source: 'workflow.py', detail: 'Custom .ai/prompts/planner.md can replace the default planning prompt. The response must still match the JSON contract.', log: 'PLAN     Request understanding, selected files, and steps.' },
  implement: { node: 'implement', title: 'Write implementation code and tests', text: 'The agent reads the selected files and asks the provider for complete file edits, verification commands, and PR metadata. The editor applies those changes locally.', input: 'Selected source files + plan + task + optional failure feedback', output: 'File edits + commands + branch/commit/PR metadata', source: 'workflow.py', detail: 'The editor supports create, modify, and delete. Paths must remain inside the checkout, but shell verification commands are not sandboxed.', log: 'EDIT     Apply complete file edits to the working tree.' },
  verify: { node: 'verify', title: 'Run the project’s verification commands', text: 'The runner executes model-provided commands, or the configured fallback. It captures output and stops at the first non-zero command exit.', input: 'Implementation commands, or .ai/config.yaml test_command', output: 'Command exit codes + captured output + tests_passed', source: 'runner.py', detail: 'Each command runs through the local shell with a 1,800-second timeout. This example illustrates commands that pass.', log: 'TEST     Example command exits 0. Verification passes.' },
  failed: { node: 'verify', title: 'Turn a test failure into feedback', text: 'A non-zero exit marks the attempt as failed. If another attempt remains, the API sends the last 6,000 characters of verification output back to the implementation step.', input: 'Failing command and captured output', output: 'Failure feedback for the next attempt', source: 'api.py', detail: 'The plan is reused. Edits from the previous attempt remain in the working tree; there is no automatic rollback.', log: 'TEST     Example command fails. Prepare failure feedback.', tone: 'warning' },
  retry: { node: 'implement', title: 'Revise the implementation', text: 'The selected files are re-read from the changed checkout. The provider receives the same plan plus the failure feedback, then returns replacement edits and commands.', input: 'Original plan + current files + failure output', output: 'Revised edits and verification commands', source: 'workflow.py', detail: 'AGENT_MAX_ITERATIONS defaults to three total implementation attempts, including the first. This trace illustrates a second attempt.', log: 'RETRY    Re-read files and apply the next implementation.' },
  exhausted: { node: 'verify', title: 'The final attempt still fails', text: 'After the configured number of attempts, the API keeps tests_passed=False and leaves the accumulated edits in the checkout.', input: 'Final non-zero verification result', output: 'tests_passed=False + last attempt output', source: 'api.py', detail: 'Current v0.1.0 behavior: PR creation is not gated on tests_passed. With open_pr=True and changes to commit, publishing can still follow.', log: 'LIMIT    Attempts exhausted. tests_passed=False.', tone: 'warning' },
  skipped: { node: 'verify', title: 'No verification command was supplied', text: 'If the model returns no commands and there is no configured fallback, the test run is skipped. The current API sets tests_passed=True in this case.', input: 'Empty command list + no fallback test_command', output: 'Tests skipped · tests_passed=True', source: 'api.py', detail: 'A true boolean is not proof that tests ran. Configure a real test command and inspect test_output and progress events.', log: 'SKIP     No commands supplied. Verification does not run.', tone: 'warning' },
  publish: { node: 'publish', title: 'Create a reviewable pull request', text: 'If changes exist, the API reads origin and the PR base, creates the model-proposed branch, stages all changes, commits, pushes, and opens a GitHub pull request.', input: 'Working-tree changes + PR metadata + GitHub token', output: 'branch + pr_url + WorkflowResult', source: 'api.py', detail: 'git add -A includes all checkout changes. Use a clean checkout. The API can reach this step even when tests failed or were skipped.', log: 'PR       Branch → commit → push → open pull request.' },
  dry: { node: 'plan', title: 'Stop here: the plan is the result', text: 'With dry_run=True, the API returns immediately after planning. No edits, verification commands, or Git publication happen.', input: 'Completed plan + dry_run=True', output: 'WorkflowResult with dry_run=True and plan text', source: 'api.py', detail: 'tests_passed is initialized to True even though no tests ran. Real-provider planning still makes a model API call.', log: 'RETURN   Dry run complete. No file edits or test execution.' },
  local: { node: 'verify', title: 'Stop here: review the local diff', text: 'With open_pr=False, the API returns the implementation result after verification. The edits stay in the checkout for your review.', input: 'Implementation result + open_pr=False', output: 'Local edits + test output · no PR URL', source: 'api.py', detail: 'The result may contain a model-proposed branch name even though no Git branch was created. Inspect git status and the full diff.', log: 'RETURN   Local result ready. No commit, push, or PR.' },
};

export const scenarios = {
  success: { label: 'Successful run', note: 'An issue-based run with a real verification command that passes.', trace: ['task', 'context', 'plan', 'implement', 'verify', 'publish'] },
  retry: { label: 'Failure & correction', note: 'The first test fails. A second implementation uses the failure feedback and passes.', trace: ['task', 'context', 'plan', 'implement', 'failed', 'retry', 'verify', 'publish'] },
  dry: { label: 'Plan only', note: '--dry-run returns after planning. A real provider still receives the planning context.', trace: ['task', 'context', 'plan', 'dry'] },
  local: { label: 'Local changes only', note: '--no-pr applies and verifies changes, then returns without any push.', trace: ['task', 'context', 'plan', 'implement', 'verify', 'local'] },
  exhausted: { label: 'Retry limit reached', note: 'Illustrates max_iterations=2. In v0.1.0, a PR can still open after the final failure.', trace: ['task', 'context', 'plan', 'implement', 'failed', 'retry', 'exhausted', 'publish'] },
  skipped: { label: 'No test command', note: 'No commands from the model or config. Tests are skipped, even though tests_passed is true.', trace: ['task', 'context', 'plan', 'implement', 'skipped', 'publish'] },
};

export function getTrace(name) {
  const scenario = scenarios[name];
  if (!scenario) throw new Error(`Unknown scenario: ${name}`);
  return scenario.trace.map(id => ({ id, ...events[id] }));
}
