"""LLM provider abstraction.

Supports Anthropic, OpenAI and a deterministic ``mock`` provider (no API key
needed) so the whole pipeline can be exercised offline. SDKs are imported lazily
so the package installs without them.
"""

from __future__ import annotations

import json
import os
from typing import Protocol

from .config import Config


class LLMError(RuntimeError):
    pass


class LLMProvider(Protocol):
    def complete(self, system: str, user: str) -> str:  # pragma: no cover - interface
        ...


class AnthropicProvider:
    def __init__(self, model: str):
        try:
            import anthropic  # noqa: F401
        except ImportError as exc:  # pragma: no cover - depends on install
            raise LLMError(
                "The 'anthropic' package is not installed. Install with: pip install 'work-issue-agent[anthropic]'"
            ) from exc
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            raise LLMError("ANTHROPIC_API_KEY is not set.")
        from anthropic import Anthropic

        self._client = Anthropic(api_key=api_key)
        self._model = model

    def complete(self, system: str, user: str) -> str:
        resp = self._client.messages.create(
            model=self._model,
            max_tokens=8192,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
        parts = [block.text for block in resp.content if getattr(block, "type", "") == "text"]
        return "\n".join(parts)


class OpenAIProvider:
    def __init__(self, model: str):
        try:
            import openai  # noqa: F401
        except ImportError as exc:  # pragma: no cover - depends on install
            raise LLMError(
                "The 'openai' package is not installed. Install with: pip install 'work-issue-agent[openai]'"
            ) from exc
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            raise LLMError("OPENAI_API_KEY is not set.")
        from openai import OpenAI

        self._client = OpenAI(api_key=api_key)
        self._model = model

    def complete(self, system: str, user: str) -> str:
        resp = self._client.chat.completions.create(
            model=self._model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        )
        return resp.choices[0].message.content or ""


class MockProvider:
    """Deterministic provider for offline testing and demos.

    It inspects the prompt to decide whether a planning or coding response is
    expected and returns valid JSON for that step.
    """

    def complete(self, system: str, user: str) -> str:
        if "PLANNING" in system or "files_to_read" in system:
            return json.dumps(
                {
                    "understanding": "Mock understanding of the request.",
                    "files_to_read": [],
                    "steps": ["Add an AGENT_NOTES.md documenting the requested change."],
                }
            )
        return json.dumps(
            {
                "summary": "Mock implementation: documents the requested change.",
                "branch": "agent/mock-change",
                "commit_message": "docs: add agent notes (mock run)",
                "pr_title": "Mock change from work-issue-agent",
                "pr_body": "This PR was generated by the mock LLM provider for testing the pipeline.",
                "edits": [
                    {
                        "path": "AGENT_NOTES.md",
                        "action": "create",
                        "content": "# Agent Notes\n\nThis file was created by the mock provider to verify the end-to-end flow.\n",
                    }
                ],
                "commands": [],
            }
        )


def get_provider(config: Config) -> LLMProvider:
    provider = config.provider
    if provider == "anthropic":
        return AnthropicProvider(config.anthropic_model)
    if provider == "openai":
        return OpenAIProvider(config.openai_model)
    if provider == "mock":
        return MockProvider()
    raise LLMError(f"Unknown LLM_PROVIDER: {provider!r} (expected anthropic|openai|mock)")
